mkdir -p media/graphics/splash/desktop;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/splash/desktop/cover.jpg -O media/graphics/splash/desktop/cover.jpg
mkdir -p media/graphics/splash/mobile;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/splash/mobile/cover.jpg -O media/graphics/splash/mobile/cover.jpg
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/bar_loading.png -O media/graphics/game/bar_loading.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/loading.png -O media/graphics/game/loading.png
mkdir -p branding;wget -c http://tools.jb51.net/static/api/games/jshrdGames/branding/splash1.png -O branding/splash1.png
mkdir -p branding;wget -c http://tools.jb51.net/static/api/games/jshrdGames/branding/logo.png -O branding/logo.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/button-more-games.png -O media/graphics/game/button-more-games.png
mkdir -p media/graphics/opening;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/opening/shield.png -O media/graphics/opening/shield.png
mkdir -p media/graphics/opening;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/opening/m_icon.png -O media/graphics/opening/m_icon.png
mkdir -p media/graphics/opening;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/opening/title.png -O media/graphics/opening/title.png
mkdir -p media/graphics/opening;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/opening/kitty.png -O media/graphics/opening/kitty.png
mkdir -p media/graphics/opening;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/opening/kittytitle.png -O media/graphics/opening/kittytitle.png
mkdir -p media/graphics/backgrounds/desktop;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/backgrounds/desktop/background.jpg -O media/graphics/backgrounds/desktop/background.jpg
mkdir -p media/graphics/backgrounds/mobile;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/backgrounds/mobile/background.jpg -O media/graphics/backgrounds/mobile/background.jpg
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/bg_title.png -O media/graphics/game/bg_title.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/logo.png -O media/graphics/game/logo.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/button-level.png -O media/graphics/game/button-level.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/button-exit.png -O media/graphics/game/button-exit.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/level-row.png -O media/graphics/game/level-row.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/select-level.png -O media/graphics/game/select-level.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/button_start.png -O media/graphics/game/button_start.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/button_options.png -O media/graphics/game/button_options.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/btn-control.png -O media/graphics/game/btn-control.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/button-pink.png -O media/graphics/game/button-pink.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/button-ok.png -O media/graphics/game/button-ok.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/popup-options.png -O media/graphics/game/popup-options.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/bg-game1.png -O media/graphics/game/bg-game1.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/blok-main.png -O media/graphics/game/blok-main.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/blok-v.png -O media/graphics/game/blok-v.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/blok-v-l.png -O media/graphics/game/blok-v-l.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/blok-h.png -O media/graphics/game/blok-h.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/blok-h-l.png -O media/graphics/game/blok-h-l.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/blok-v-t.png -O media/graphics/game/blok-v-t.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/blok-vl-t.png -O media/graphics/game/blok-vl-t.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/blok-h-t.png -O media/graphics/game/blok-h-t.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/blok-hl-t.png -O media/graphics/game/blok-hl-t.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/blok-m-t.png -O media/graphics/game/blok-m-t.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/navigation.png -O media/graphics/game/navigation.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/button-replay.png -O media/graphics/game/button-replay.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/level-complete.png -O media/graphics/game/level-complete.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/khung-go-main.png -O media/graphics/game/khung-go-main.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/button-pause.png -O media/graphics/game/button-pause.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/hud-level.png -O media/graphics/game/hud-level.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/button-settings.png -O media/graphics/game/button-settings.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/hud-moves.png -O media/graphics/game/hud-moves.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/button-retry.png -O media/graphics/game/button-retry.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/button-hint.png -O media/graphics/game/button-hint.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/arrow.png -O media/graphics/game/arrow.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/star.png -O media/graphics/game/star.png
mkdir -p media/graphics/game;wget -c http://tools.jb51.net/static/api/games/jshrdGames/media/graphics/game/star2.png -O media/graphics/game/star2.png
