function FinishScreen(){Resizable.call(this);this.bar0=new Sprite;this.bar1=new Sprite;this.bars=new Sprite;this.addChild(this.bars);this.bar0.graphics.beginFill(0);this.bar0.graphics.drawRect(0,0,1,.25);this.bar1.graphics.beginFill(0);this.bar1.graphics.drawRect(0,0,1,.25);this.bars.addChild(this.bar0);this.bars.addChild(this.bar1);this.cont=new Sprite;this.addChild(this.cont);this.wd=new CText("Well done!",16,100);this.wd.x=(1024-this.wd.getRect(this).width)/2;this.cont.addChild(this.wd);this.sb=
new StarBar;this.sb.x=320;this.cont.addChild(this.sb);this.bb=new ButtonBar;this.bb.x=(1024-.8*448)/2;this.bb.scaleX=this.bb.scaleY=.8;this.cont.addChild(this.bb);this.Hide()}FinishScreen.prototype=new Resizable;
FinishScreen.prototype.Show=function(a,b,d){this.resize(this.w,this.h);this.visible=!0;a=Rules.GetStars(a,b,d);Tweener.addTween(this.bar0,{y:0,transition:"easeInSine",time:.3});Tweener.addTween(this.bar1,{y:.75,transition:"easeInSine",time:.3});Tweener.addTween(this.wd,{alpha:1,y:280,transition:"easeOutBack",delay:.3,time:.4});Tweener.addTween(this.sb,{alpha:1,y:500,transition:"easeOutBack",delay:.7,time:.4});Tweener.addTween(this.bb,{alpha:1,y:700,transition:"easeOutBack",delay:1+.5*a,time:.5});
this.sb.ShowStars(a,1.3)};FinishScreen.prototype.Hide=function(){this.visible=!1;this.bar0.y=-.25;this.bar1.y=1;this.wd.y=-this.wd.getRect(this).height;this.sb.y=1024;this.bb.y=1024;this.wd.alpha=this.sb.alpha=this.bb.alpha=0};FinishScreen.prototype.resize=function(a,b){this.w=a;this.h=b;this.bars.scaleX=a;this.bars.scaleY=b;var d=Math.min(a,b)/1024;this.cont.x=this.cont.y=0;this.cont.scaleX=this.cont.scaleY=d;a>b?this.cont.x=(a-1024*d)/2:this.cont.y=(b-1024*d)/2};
function ButtonBar(){Sprite.call(this);this.buttonMode=!0;for(var a=0;3>a;a++){var b=new Bitmap(BDFac.get("btn"));this.addChild(b);b.x=160*a}a=new Bitmap(BDFac.get("btn_go"));a.x=a.y=128;a.rotation=180;this.addChild(a);this.back=a;a=new Bitmap(BDFac.get("btn_reload"));a.x=160;this.addChild(a);this.rest=a;a=new Bitmap(BDFac.get("btn_go"));a.x=320;this.addChild(a);this.next=a;this.addEventListener2(MouseEvent.CLICK,this.onCL,this)}ButtonBar.prototype=new Sprite;
ButtonBar.prototype.onCL=function(a){a.target==this.back&&this.dispatchEvent(new Event("exitBack",!0));a.target==this.rest&&this.dispatchEvent(new Event("exitRest",!0));a.target==this.next&&this.dispatchEvent(new Event("exitNext",!0))};
function TopMenu(a){Sprite.call(this);this.t=0;this.btns=[];for(var b=this.ang=0;b<a.length;b++){var d=new TopBTN(a[b],View.colors[b]);d.ind=b;d.addEventListener2(MouseEvent.CLICK,this.packChosen,this);d.x=(1024-d.getRect(d).width)/2;d.y=1030+90*b;Tweener.addTween(d,{y:420+90*b,transition:"easeOutBack",time:.5,delay:1+.2*b});this.addChild(d);this.btns.push(d)}this.lcont=new Sprite;this.lcont.mouseEnabled=this.lcont.mouseChildren=!1;this.logo=new Bitmap(BDFac.get("logo"));this.logo.x=-512;this.logo.y=
-200;this.lcont.addChild(this.logo);this.lcont.scaleX=this.lcont.scaleY=.9;this.lcont.x=512;this.addChild(this.lcont);this.spinLogo();this.addEventListener2(Event.ENTER_FRAME,this.onEF,this)}TopMenu.prototype=new Sprite;TopMenu.prototype.spinLogo=function(){this.lcont.rotationY=90;Tweener.addTween(this.lcont,{rotationY:360,transition:"easeOutElastic",delay:.5,time:2})};TopMenu.prototype.Update=function(a,b,d){for(var g=0;g<this.btns.length;g++)this.btns[g].Update(a[g].length,b[g],d)};
TopMenu.prototype.packChosen=function(a){var b=new Event("packChosen",!0);b.ind=a.currentTarget.ind;this.dispatchEvent(b)};TopMenu.prototype.onEF=function(a){this.t++;a=this.ang+=.06;this.lcont.y=200+16*Math.sin(a);this.lcont.scaleX=.9+.05*Math.sin(-a)};
function TopBTN(a,b){Sprite.call(this);this.buttonMode=!0;this.graphics.beginFill(b);this.graphics.drawRoundRect(0,0,700,76,30,30);this.tf=new TextField;this.tf.selectable=!1;this.tfr=new TextFormat("Trebuchet MS",48,16777215,!0);this.tf.setTextFormat(this.tfr);this.tf.text=a.name;this.tf.width=this.tf.textWidth;this.tf.height=this.tf.textHeight;this.addChild(this.tf);this.tf.x=20;this.tf.y=8;this.tf2=new TextField;this.tf2.selectable=!1;this.tf2.setTextFormat(this.tfr);this.addChild(this.tf2);this.Update(0,
a)}TopBTN.prototype=new Sprite;TopBTN.prototype.Update=function(a,b,d){this.tf2.text=Math.min(d,a)+"/"+Math.min(d,b.maps.length);this.tf2.width=this.tf2.textWidth;this.tf2.height=this.tf2.textHeight;this.tf2.x=700-this.tf2.width-20;this.tf2.y=8};
function MenuBG(){Resizable.call(this);this.graphics.beginFill(1118481);this.graphics.drawRect(-5E3,-5E3,1E4,1E4);this.star=new Sprite;this.addChild(this.star);var a=(new Date).getMonth();this.sky=new Sky(0,Math.floor((a+7)%12/3),!1);this.addChild(this.sky);for(var a=2*Math.PI/16,b=[0,0],d=[],g=0;16>g;g++){var f=g*a;b.push(3E3*Math.cos(f),3E3*Math.sin(f));b.push(3E3*Math.cos(f+.65*a),3E3*Math.sin(f+.65*a))}for(g=1;16>g;g++)d.push(0,2*g,2*g+1);d.push(0,32,1);this.star.graphics.beginFill(16777215,.16);
this.star.graphics.drawTriangles(b,d);this.addEventListener2(Event.ENTER_FRAME,this.onEF,this)}MenuBG.prototype=new Resizable;MenuBG.prototype.resize=function(a,b){this.star.x=.5*a;this.star.y=.3*b;this.star.z=-2;this.sky.resize(a,b)};MenuBG.prototype.onEF=function(a){this.star.rotation+=.2};
function CText(a,b,d){Sprite.apply(this);this.mouseChildren=!1;d||(d=24);this.tf=new TextField;this.tf.selectable=!1;this.addChild(this.tf);d&&(CText.tfr.size=d);this.tf.setTextFormat(CText.tfr);this.tf.x=Math.floor(1.4*b);this.pad=this.tf.y=b;this.SetText(a)}CText.prototype=new Sprite;CText.tfr=new TextFormat("Trebuchet MS",24,16777215,!0);
CText.prototype.SetText=function(a){if(a!=this.tf.text){this.tf.text=a;a=this.pad;var b=this.tf.textWidth,d=this.tf.textHeight+1;this.tf.width=b;this.tf.height=d;this.graphics.clear();this.graphics.beginFill(0);this.graphics.drawRoundRect(0,0,b+2*this.tf.x,d+2*this.tf.y,2*a,2*a)}};function StarBar(){Sprite.call(this);this.stars=[];for(var a=0;3>a;a++){var b=new Bitmap(BDFac.get("star_gray"));b.x=128*a;this.addChild(b);b=new StarBar.Star;b.x=64+128*a;b.y=64;this.addChild(b);this.stars.push(b)}}
StarBar.prototype=new Sprite;StarBar.prototype.ShowStars=function(a,b,d){b||(b=0);null==d&&(d=!0);for(var g=0;g<this.stars.length;g++){var f=this.stars[g];f.alpha=0;g<a&&(f.scaleX=f.scaleY=2,Tweener.addTween(f,{alpha:1,scaleX:1,scaleY:1,transition:"easeOutElastic",delay:b+.5*g,time:.7}),d&&setTimeout(CSound.playOnce,1E3*(b+.5*g+.1),"kick"))}};StarBar.prototype.ShowStarsNow=function(a){for(var b=0;b<this.stars.length;b++)this.stars[b].alpha=b<a?1:0};
StarBar.Star=function(){Sprite.call(this);var a=new Bitmap(BDFac.get("star"));a.x=a.y=-64;this.addChild(a)};StarBar.Star.prototype=new Sprite;
function Icon(a){Sprite.call(this);this.mouseChildren=!1;this.buttonMode=!0;this.level=a;null==Icon.tex&&(Icon.tex=new BitmapData("img/icon_bg.png"),Icon.TF=new TextFormat("Trebuchet MS",54,0,!0));this.level=a;var b=this.graphics;b.beginFill(16777215);b.drawRect(-62,-84,124,124);b.beginFill(0);b.drawRect(-62,40,124,44);this.scaleX=this.scaleY=.8;b=new TextField;b.selectable=!1;b.setTextFormat(Icon.TF);b.text=a+1;b.width=b.textWidth;b.height=b.textHeight;b.x=-b.width/2;b.y=-54;this.addChild(b);this.numTXT=
b;this.stars=new StarBar;this.stars.scaleX=this.stars.scaleY=.28;this.stars.x=-53;this.stars.y=43;this.stars.ShowStars(0);this.addChild(this.stars);this.addEventListener2(MouseEvent.MOUSE_OVER,this.mark,this);this.addEventListener2(MouseEvent.MOUSE_OUT,this.unmark,this)}Icon.prototype=new Sprite;Icon.prototype.Update=function(a,b,d){this.numTXT.text=a+1;this.numTXT.width=this.numTXT.textWidth;this.numTXT.x=-this.numTXT.width/2;(this.visible=b)&&this.snum!=d&&(this.snum=d,this.stars.ShowStarsNow(d))};
Icon.prototype.mark=function(a){Tweener.addTween(this,{scaleX:1,scaleY:1,transition:"easeOutElastic",time:.6})};Icon.prototype.unmark=function(a){Tweener.addTween(this,{scaleX:.8,scaleY:.8,transition:"easeOutElastic",time:.6})};function SoundBTN(){Sprite.call(this);this.buttonMode=!0;this.addChild(new Bitmap(BDFac.get("sound")));this.addEventListener2(MouseEvent.CLICK,this.onCL,this)}SoundBTN.prototype=new Sprite;SoundBTN.prototype.onCL=function(a){this.alpha=1==this.alpha?.3:1;this.dispatchEvent(new Event(Event.CHANGE))};
function HelpPanel(){Sprite.call(this);this.hidden=!0;this.panel=new Sprite;this.addChild(this.panel);this.panel.graphics.beginFill(0);this.panel.graphics.drawRoundRect(0,0,800,600,100,100);this.panel.x=112;var a=new TextFormat("Trebuchet MS",45,16777215,!0),b=new TextField;b.selectable=!1;b.setTextFormat(a);b.text="How to solve Connection";b.width=b.textWidth;b.height=b.textHeight;b.x=(800-b.width)/2;b.y=64;this.panel.addChild(b);a.size=35;a.align=TextFormatAlign.JUSTIFY;b=new TextField;b.selectable=
!1;b.wordWrap=!0;b.setTextFormat(a);b.text="There is a magic square grid and tiny monsters are all over it. Your job is to connect each two monsters having the same color with a line. Connection lines should not cross each other.";b.width=700;b.height=400;this.panel.addChild(b);b.x=50;b.y=160;this.panel.y=-700;this.panel.alpha=0}HelpPanel.prototype=new Sprite;HelpPanel.prototype.Hide=function(){this.hidden=!0;Tweener.addTween(this.panel,{y:-700,alpha:0,transition:"easeInBack",time:1})};
HelpPanel.prototype.Show=function(){this.hidden=!1;Tweener.addTween(this.panel,{y:212,alpha:1,transition:"easeOutBack",time:1})};function ConnMain(){Main.call(this);this.mm=new ConnMenu;this.ls=new ConnSelect;this.gc=new ConnControl;this.addChild(this.mm)}ConnMain.prototype=new Main;
function ConnMenu(){MainMenu.call(this);BDFac.load("intro","img/intro.png");BDFac.load("sky","img/winter.jpg");BDFac.load("logo","img/logo.png");BDFac.load("star_gray","img/star_gray.png");BDFac.load("star","img/star.png");BDFac.load("sound","img/snd.png");BDFac.load("btn","img/btn.png");BDFac.load("btn_reload","img/btn_reload.png");BDFac.load("btn_go","img/btn_go.png");BDFac.load("m_eye","img/meye.png");BDFac.load("m_eye_dot","img/meyeDot.png");BDFac.addEventListener2(Event.COMPLETE,this.showIntro,
this)}ConnMenu.prototype=new MainMenu;ConnMenu.prototype.showIntro=function(a){this.resize(this.w,this.h);this.GoPlay()};ConnMenu.prototype.resize=function(a,b){this.w=a;this.h=b;this.cont&&this.cont.resize(a,b)};
function ConnSelect(){LevelSelect.call(this);this.DSTR=!1;ConnSelect._main=this;this.bg=new MenuBG;this.addChild(this.bg);this.bg.z=500;this.udata=this.scores=null;this.cpack=-1;this.mapOffset=0;this.cmap=-1;var a=new XMLHttpRequest;a.addEventListener("load",this.packsLoaded.bind(this),!1);this.DSTR?a.open("GET","js/packs.json",!0):a.open("GET","js/packs.json",!0);a.send(null);this.addEventListener2(Event.ADDED_TO_STAGE,this.onATS,this)}ConnSelect.prototype=new LevelSelect;
ConnSelect.prototype.packsLoaded=function(a){this.packs=JSON.parse(a.target.response).packs;this.init()};
ConnSelect.prototype.onATS=function(a){this.removeEventListener(Event.ADDED_TO_STAGE,this.onATS);null!=this.packs&&(this.tm=new TopMenu(this.packs),this.addChild(this.tm),this.tm.Update(this.scores,this.packs,this.udata.unlocked),this.mcont=new MarginCont(1024,32),this.addChild(this.mcont),this.sndBTN=new SoundBTN,this.sndBTN.addEventListener2(Event.CHANGE,this.soundChange,this),this.sndBTN.scaleX=this.sndBTN.scaleY=1.6,this.mcont.add(this.sndBTN,0),this.hp=new HelpPanel,this.hp.z=-2,this.addChild(this.hp),
this.helpBTN=new CText("Help",10,42),this.helpBTN.buttonMode=!0,this.helpBTN.addEventListener2(MouseEvent.CLICK,this.showHideHelp,this),this.mcont.add(this.helpBTN,3),this.icons=[],this.pm=new Sprite,this.initPackMenu(),this.addEventListener2("packChosen",this.packChosen,this),this.addEventListener2("mapChosen",this.mapChosen,this),this.nmTXT=new CText(this.packs.length+" x 10 new levels will be unlocked in "+Math.ceil(24-(Date.now()-this.udata.utime)/36E5)+" hours.",12,24),0==this.DSTR&&this.mcont.add(this.nmTXT,
2),CSound.play("intro_loop",.5),this.resize(this.w,this.h))};ConnSelect.prototype.init=function(){this.udata=this.GetUserData();this.scores=this.udata.scores;this.SaveUserData(this.udata);this.decodeMaps(this.packs);if(null!=this.stage)this.onATS(null)};ConnSelect.prototype.decodeMaps=function(a){for(var b=0;b<a.length;b++){var d=a[b],g=atob(d.levels);d.maps=[];for(var f=0;f<g.length;f+=2*d.colors){var k=g.slice(f,f+2*d.colors),k=ConnSelect.dcMap(k,d.size);d.maps.push(k)}}};
ConnSelect.dcMap=function(a,b){for(var d=b*b,g=[],f=0;f<d;f++)g.push(-1);for(f=0;f<a.length/2;f++){var d=a.charCodeAt(2*f),k=a.charCodeAt(2*f+1);g[d]=g[k]=f}return g};
ConnSelect.prototype.resize=function(a,b){this.w=a;this.h=b;this.bg.resize(a,b);if(null!=this.packs&&null!=this.mcont){this.mcont.resize(a,b);var d=Math.min(a,b)/1024;this.tm.x=this.tm.y=0;this.tm.scaleX=this.tm.scaleY=d;a>b?this.tm.x=(a-1024*d)/2:this.tm.y=(b-1024*d)/2;this.hp.scaleX=this.hp.scaleY=d;this.hp.x=this.tm.x;this.hp.y=this.tm.y;var g=this.pm;g.x=this.tm.x;g.y=this.tm.y;g.scaleX=g.scaleY=d}};
ConnSelect.prototype.LevelDone=function(a){CSound.on&&CSound.play("intro_loop",.5);-1!=a.time&&(a.time=Math.round(100*a.time)/100,null==this.scores[this.cpack][this.cmap]&&(this.scores[this.cpack][this.cmap]=9999999),this.scores[this.cpack][this.cmap]=Math.min(this.scores[this.cpack][this.cmap],a.time),this.SaveUserData(this.udata),1==a.action&&this.goPlayGame(),2==a.action&&this.cmap!=Math.min(this.packs[this.cpack].maps.length,this.udata.unlocked)-1&&(this.cmap++,this.goPlayGame()),this.tm.Update(this.scores,
this.packs,this.udata.unlocked),this.updateIcons())};ConnSelect.prototype.showHideHelp=function(a){this.setChildIndex(this.hp,this.numChildren-1);this.hp.hidden?this.hp.Show():this.hp.Hide()};ConnSelect.prototype.packChosen=function(a){this.switchPack(a.ind);this.nmTXT.visible=!1};ConnSelect.prototype.soundChange=function(a){CSound.on=CSound.on?!1:!0;CSound.on?CSound.play("intro_loop",.5):CSound.stop("intro_loop")};
ConnSelect.prototype.showTopMenu=function(){this.nmTXT.visible=!0;this.contains(this.pm)&&(this.removeChild(this.pm),this.addChild(this.tm))};ConnSelect.prototype.switchPack=function(a){this.mapOffset=0;this.cpack=a;this.contains(this.tm)&&(this.removeChild(this.tm),this.addChild(this.pm));this.pm.caption.SetText(this.packs[a].name);this.pm.caption.x=(1024-this.pm.caption.getRect(this.pm).width)/2;this.updateIcons()};
ConnSelect.prototype.mapChosen=function(a){this.cmap=a.currentTarget.ind+this.mapOffset;this.goPlayGame()};ConnSelect.prototype.goPlayGame=function(){var a=this.packs[this.cpack];this.levelData.size=a.size;this.levelData.colors=a.colors;this.levelData.map=a.maps[this.cmap];this.levelData.ind=this.cmap;this.LevelChosen();CSound.stop("intro_loop")};
ConnSelect.prototype.initPackMenu=function(){var a=this.pm;a.caption=new CText("Hoo",10,70);a.addChild(a.caption);a.caption.y=70;for(var b=0;20>b;b++){var d=new Icon(b);d.addEventListener2(MouseEvent.CLICK,this.mapChosen,this);d.ind=b;a.addChild(d);d.x=100+b%5*824/4;d.y=300+156*Math.floor(b/5);this.icons.push(d)}var b=new CText("<",10,60),d=new CText(">",10,60),g=new CText("Home",10,60);b.buttonMode=d.buttonMode=g.buttonMode=!0;b.y=d.y=g.y=880;b.x=316;d.x=640;g.x=412;a.addChild(b);a.addChild(d);a.addChild(g);
b.addEventListener2(MouseEvent.CLICK,this.shiftL,this);d.addEventListener2(MouseEvent.CLICK,this.shiftR,this);g.addEventListener2(MouseEvent.CLICK,this.showTopMenu,this)};ConnSelect.prototype.shiftL=function(a){this.mapOffset=Math.max(0,this.mapOffset-20);this.updateIcons()};ConnSelect.prototype.shiftR=function(a){this.mapOffset=Math.min(20*Math.floor(Math.min(Math.min(this.udata.unlocked-1,this.scores[this.cpack].length),this.packs[this.cpack].maps.length-1)/20),this.mapOffset+20);this.updateIcons()};
ConnSelect.prototype.updateIcons=function(){var a=this.scores[this.cpack],b=this.packs[this.cpack];c;for(var d=Math.min(this.udata.unlocked,b.maps.length),g=Math.min(20,a.length-this.mapOffset,d-this.mapOffset),f=0;20>f;f++){var k=this.mapOffset+f,n=a[k];this.icons[f].Update(k,f<g||f==g&&f<d-this.mapOffset,Rules.GetStars(n?n:99999,b.size,b.colors))}};
ConnSelect.prototype.GetUserData=function(){var a=localStorage.connection_scores,a=a?JSON.parse(a):{scores:[],unlocked:10,utime:Date.now()};24<(Date.now()-a.utime)/36E5&&(a.unlocked+=10,a.utime=Date.now());this.DSTR&&(a.unlocked=99999999);for(;a.scores.length>this.packs.length;)a.scores.splice(0,1);for(;a.scores.length<this.packs.length;)a.scores.push([]);return a};ConnSelect.prototype.SaveUserData=function(a){localStorage.connection_scores=JSON.stringify(a)};
var Rules={GetStars:function(a,b,d){a/=b*b-2*d;return.8>a?3:1>a?2:1.5>a?1:0}};
function ConnControl(){GameControl.call(this);this.MARGIN=22;this.time=this.timeStart=0;this.fs=new FinishScreen;this.addChild(this.fs);this.levelData=null;this.mcont=new MarginCont(1024,32);this.addChild(this.mcont);this.levelTXT=new CText("Level X",8,36);this.mcont.add(this.levelTXT,0);this.timeTXT=new CText(" ",8,36);this.mcont.add(this.timeTXT,0);this.backBTN=new CText("Back",12,42);this.backBTN.buttonMode=!0;this.backBTN.addEventListener2(MouseEvent.CLICK,this.exitGame,this);this.mcont.add(this.backBTN,
2);this.mask=new Sprite;this.mask.mouseEnabled=!1;this.mask.graphics.beginFill(0);this.mask.graphics.drawRect(0,0,1,1);this.addChild(this.mask);this.addEventListener2("exitBack",this.onDone,this);this.addEventListener2("exitRest",this.onDone,this);this.addEventListener2("exitNext",this.onDone,this);this.addEventListener2(Event.ENTER_FRAME,this.onEF,this);this.game=null}ConnControl.prototype=new GameControl;
ConnControl.prototype.onEF=function(a){this.game&&!this.game.paused&&(this.time=.001*((new Date).getTime()-this.timeStart),this.timeTXT.SetText(Math.floor(this.time)+" sec"))};
ConnControl.prototype.StartLevel=function(a){CSound.play("game_loop",.5);this.levelData=a;this.time=0;this.timeStart=(new Date).getTime();this.game=new Controller(a);this.game.addEventListener2(Event.COMPLETE,this.onComplete,this);this.addChild(this.game);this.setChildIndex(this.game,0);this.timeTXT.SetText("0:00");this.levelTXT.SetText("Level "+(a.ind+1));this.fs.Hide();this.mask.alpha=1;Tweener.addTween(this.mask,{alpha:0,transition:"easeInOutSine",time:.5});this.resize(this.w,this.h)};
ConnControl.prototype.onComplete=function(a){this.game.paused=!0;CSound.playOnce("tada");this.fs.Show(this.time,this.levelData.size,this.levelData.colors)};ConnControl.prototype.onDone=function(a){this.result.time=this.time;this.result.action="exitBack"==a.type?0:"exitRest"==a.type?1:2;this.Destruct();this.GameDone()};ConnControl.prototype.exitGame=function(a){this.Destruct();this.result.time=-1;this.GameDone()};
ConnControl.prototype.Destruct=function(){CSound.stop("game_loop");this.game.Destruct();this.game.removeEventListener("cutDone",this.onCut);this.game.removeEventListener("dead",this.onDead);this.game.removeEventListener("timeChange",this.onTimeChange);this.removeChild(this.game)};ConnControl.prototype.resize=function(a,b){this.w=a;this.h=b;this.mcont.resize(a,b);this.mask.scaleX=a;this.mask.scaleY=b;this.game&&this.game.resize(a,b);this.fs.resize(a,b)};
function Model(a){this.size=a.size;this.colors=a.colors;this.map=a.map;this.drawing=!1;this.paths=[];this.curpos=this.curc=-1;this.newPath=this.changed=!1;for(var b=0;b<a.colors;b++)this.paths.push([])}Model.prototype.IsConnected=function(){for(var a=!0,b=0;b<this.colors;b++){var d=this.paths[b];if(3>d.length)return!1;if(map[d[0]]!=b||map[d[d.length-1]]!=b)a=!1}return a};Model.prototype.NewPath=function(){var a=this.newPath;this.newPath=!1;return a};
Model.prototype.IsComplete=function(){for(var a=0,b=0;b<this.colors;b++)a+=this.paths[b].length;return a==this.size*this.size};Model.prototype.WasChanged=function(){var a=this.changed;this.changed=!1;return a};
Model.prototype.StartPath=function(a,b){var d=b*this.size+a;this.curpos=d;this.changed=!0;if(-1!=this.map[d])this.curc=this.map[d],this.paths[this.curc]=[d],this.drawing=!0;else for(var g=0;g<this.paths.length;g++){var f=this.paths[g].indexOf(d);if(-1<f){this.curc=g;this.paths[g]=this.paths[g].slice(0,f+1);this.drawing=!0;break}}};
Model.prototype.Move=function(a,b){if(this.drawing){var d=b*this.size+a,g=this.curpos,f=this.size;if(d!=g&&(d==g+-1||d==g+1||d==g-f||d==g+f))if(-1==this.map[d]){this.curpos=d;this.changed=!0;for(g=0;g<this.colors;g++)if(f=this.paths[g].indexOf(d),-1<f){this.paths[g]=this.paths[g].slice(0,f);break}this.paths[this.curc].push(d)}else this.map[d]==this.curc&&(this.curpos=d,this.changed=!0,this.paths[this.curc][0]==d?this.paths[this.curc]=[]:(this.EndPath(),this.newPath=!0),this.paths[this.curc].push(d))}};
Model.prototype.EndPath=function(){this.drawing=!1};
function View(a){Resizable.call(this);this.model=a;this.mouseChildren=this.mouseEnabled=!1;this.cont=new Sprite;this.addChild(this.cont);this.monsters=[];var b=View.tsize*a.size;this.cont.graphics.beginFill(0,.7);this.cont.graphics.drawRect(-30,-30,b+60,b+60);this.cont.graphics.endFill();this.cont.graphics.lineStyle(6,16777215);for(var d=0;d<=a.size;d++){var g=d*View.tsize;this.cont.graphics.moveTo(g,0);this.cont.graphics.lineTo(g,b);this.cont.graphics.moveTo(0,g);this.cont.graphics.lineTo(b,g)}this.lines=
new Sprite;this.lines.x=this.lines.y=View.tsize/2;this.lines.scaleX=this.lines.scaleY=View.tsize;this.cont.addChild(this.lines);for(d=0;d<a.map.length;d++)-1!=a.map[d]&&(b=new Monster(a.map[d]),b.scaleX=b.scaleY=0,Tweener.addTween(b,{scaleX:1,scaleY:1,transition:"easeOutElastic",delay:.1*this.monsters.length,time:1}),b.x=View.tsize*(.5+d%a.size),b.y=View.tsize*(.5+Math.floor(d/a.size)),this.cont.addChild(b),this.monsters.push(b))}View.prototype=new Resizable;
View.prototype.ShowPath=function(a){for(var b=0;b<this.monsters.length;b++){var d=this.monsters[b];d.color==a&&(Tweener.addTween(d,{scaleX:1.3,scaleY:.7,transition:"easeInOutSine",time:.3}),Tweener.addTween(d,{scaleX:.7,scaleY:1.3,transition:"easeInOutSine",time:.2,delay:.3}),Tweener.addTween(d,{scaleX:1,scaleY:1,transition:"easeOutElastic",time:.5,delay:.5}))}};View.tsize=256;View.colors=[14492160,2280448,2237149,15658496,56797,11141290,14540253,16746496,16742314,13056];
View.prototype.Update=function(){var a=this.model.size;this.lines.graphics.clear();for(var b=0;b<this.model.colors;b++){var d=this.model.paths[b];this.lines.graphics.lineStyle(.25,View.colors[b]);this.lines.graphics.moveTo(d[0]%a,Math.floor(d[0]/a));for(var g=1;g<d.length;g++)this.lines.graphics.lineTo(d[g]%a,Math.floor(d[g]/a))}};
function Controller(a){Resizable.call(this);this.paused=!1;this.time=0;this.sky=new Sky(4,2);this.addChild(this.sky);this.model=new Model(a);this.view=new View(this.model);this.addChild(this.view);this.tcEv=new Event("timeChange");this.addEventListener2(Event.ADDED_TO_STAGE,this.onATS,this)}Controller.prototype=new Resizable;
Controller.prototype.resize=function(a,b){this.w=a;this.h=b;this.sky.resize(a,b);var d=this.model.size*View.tsize,g=.9*Math.min(a/d,b/d);this.view.scaleX=this.view.scaleY=g;this.view.x=(a-d*g)/2;this.view.y=(b-d*g)/2};Controller.prototype.Destruct=function(){this.removeChild(this.sky);this.sky.Destruct();this.stage.removeEventListener(MouseEvent.MOUSE_DOWN,this.onMD);this.stage.removeEventListener(MouseEvent.MOUSE_UP,this.onMU);this.stage.removeEventListener(MouseEvent.MOUSE_MOVE,this.onMM)};
Controller.prototype.onATS=function(a){this.removeEventListener(Event.ADDED_TO_STAGE,this.onATS);this.stage.addEventListener2(MouseEvent.MOUSE_DOWN,this.onMD,this);this.stage.addEventListener2(MouseEvent.MOUSE_UP,this.onMU,this);this.stage.addEventListener2(MouseEvent.MOUSE_MOVE,this.onMM,this)};
Controller.prototype.Update=function(a){this.model.WasChanged()&&(this.view&&this.view.Update(),this.model.NewPath()&&(CSound.playOnce("unlock"),this.view.ShowPath(this.model.curc)));this.model.IsComplete()&&this.dispatchEvent(new Event(Event.COMPLETE))};Controller.prototype.onMD=function(a){!this.paused&&(a=this.getCell())&&(this.model.StartPath(a.x,a.y),this.Update())};Controller.prototype.onMM=function(a){!this.paused&&(a=this.getCell())&&(this.model.Move(a.x,a.y),this.Update())};
Controller.prototype.onMU=function(a){this.model.EndPath()};Controller.prototype.getCell=function(){var a=this.model.size,b=Math.floor(this.view.mouseX/View.tsize),d=Math.floor(this.view.mouseY/View.tsize);return-1<b&&-1<d&&b<a&&d<a?new Point(b,d):null};
function Sky(a,b,d){Resizable.call(this);this.w=this.h=400;this.time=0;null==d&&(d=!0);this.mouseChildren=this.mouseEnabled=!1;var g=Math.random()*Math.PI;this.wind=new Point(Math.cos(g),Math.sin(g));this.level=a;this.season=b;this.lw=800;this.lh=600;this.bits=[];d&&(this.bg=new Bitmap(BDFac.get("sky")),this.addChild(this.bg));this.bcont=new Sprite;this.addChild(this.bcont)}Sky.prototype=new Resizable;
Sky.prototype.Destruct=function(){this.removeEventListener(Event.ADDED_TO_STAGE,this.onATS);this.removeEventListener(Event.REMOVED_FROM_STAGE,this.onRFS)};Sky.prototype.onATS=function(){this.addEventListener2(Event.ENTER_FRAME,this.onEF,this)};Sky.prototype.onRFS=function(){this.removeEventListener(Event.ENTER_FRAME,this.onEF)};
Sky.prototype.resize=function(a,b){this.w=a;this.h=b;this.bg&&(this.bg.scaleX=a/1024,this.bg.scaleY=b/512);var d=a/b;this.lh=Math.sqrt(this.lw*this.lh/d);this.lw=d*this.lh;this.bcont.scaleX=this.bcont.scaleY=a/this.lw};
Sky.prototype.onEF=function(a){this.time++;a=this.bits.length;for(var b=this.season,d=this.wind,g=0;g<a;g++){var f=this.bits[g];f.ang+=f.dang;f.x+=f.vel*Math.cos(f.ang);f.y+=f.vel*Math.sin(f.ang);f.x+=d.x*(.3+.16/f.scale);f.y+=d.y*(.3+.16/f.scale);0<b?(f.scaleX=.7*f.scale,f.rotation=-20*f.ang):f.rotation=30*Math.sin(f.ang);-50>f.y?(f.y=this.lh+50,f.x=Math.random()*this.w):f.y>this.lh+50&&(f.y=-50,f.x=Math.random()*this.lw);-50>f.x?f.x=this.lw+50:f.x>this.lw+50&&(f.x=-50)}};
function Monster(a){Sprite.call(this);this.color=a;this.effTime=0;null==Monster.eyeBD&&(Monster.eyeBD=new BitmapData("img/flyEyes.png"));if(null==Monster.bodyBDs){Monster.bodyBDs=[];for(var b=0;b<View.colors.length;b++){var d=new BitmapData("img/mbody.png");d.loader.color=View.colors[b];d.loader.addEventListener(Event.COMPLETE,Monster.bodyLoaded);Monster.bodyBDs.push(d)}}this.body=new Bitmap(Monster.bodyBDs[a]);this.body.scaleX=this.body.scaleY=.78125;this.body.x=this.body.y=-100;this.addChild(this.body);
this.eyeL=new MEye;this.eyeR=new MEye;this.addChild(this.eyeL);this.addChild(this.eyeR);this.eyeL.scaleX=this.eyeL.scaleY=.5+.2*Math.random();this.eyeR.scaleX=this.eyeR.scaleY=.5+.2*Math.random();this.eyeL.y=this.eyeR.y=-20;this.eyeL.x=-40;this.eyeR.x=40;this.addEventListener2(Event.ENTER_FRAME,this.onEF,this);this.addEventListener2(Event.REMOVED_FROM_STAGE,this.onRFS,this)}Monster.prototype=new Sprite;
Monster.prototype.onRFS=function(a){this.removeEventListener(Event.ENTER_FRAME,this.onEF);this.removeEventListener(Event.REMOVED_FROM_STAGE,this.onRFS)};
Monster.prototype.onEF=function(a){this.effTime-=1/60;if(!(0<this.effTime||.02<Math.random()))if(this.effTime=3,.8>Math.random()){if(a=new Point(this.mouseX,this.mouseY),0!=a.x||0!=a.y){var b=Math.sqrt(a.x*a.x+a.y*a.y);a.x/=b;a.y/=b;Tweener.addTween(this.eyeL.dot,{x:-16+30*a.x,y:-16+30*a.y,transition:"easeInOutSine",time:.5});Tweener.addTween(this.eyeR.dot,{x:-16+30*a.x,y:-16+30*a.y,transition:"easeInOutSine",time:.5});Tweener.addTween(this.eyeL.dot,{x:-16,y:-16,transition:"easeInOutSine",delay:1,
time:.5});Tweener.addTween(this.eyeR.dot,{x:-16,y:-16,transition:"easeInOutSine",delay:1,time:.5})}}else a=this.eyeL.scaleX,Tweener.addTween(this.eyeL,{scaleX:.2*a,scaleY:.2*a,transition:"easeInOutSine",time:.2}),Tweener.addTween(this.eyeL,{scaleX:a,scaleY:a,transition:"easeInOutSine",delay:.3,time:.2}),a=this.eyeR.scaleX,Tweener.addTween(this.eyeR,{scaleX:.2*a,scaleY:.2*a,transition:"easeInOutSine",time:.2}),Tweener.addTween(this.eyeR,{scaleX:a,scaleY:a,transition:"easeInOutSine",delay:.3,time:.2})};
Monster.bodyLoaded=function(a){var b=a.target.bitmapData,d=a.target.color;a=Math.floor(d>>16&255);for(var g=Math.floor(d>>8&255),d=Math.floor(d>>0&255),f=b.getPixels(b.rect),k=0;k<f.length;k+=4)f[k]=a,f[k+1]=g,f[k+2]=d;b.setPixels(b.rect,f)};function MEye(){Sprite.call(this);this.bg=new Bitmap(BDFac.get("m_eye"));this.addChild(this.bg);this.bg.x=this.bg.y=-64;this.dot=new Bitmap(BDFac.get("m_eye_dot"));this.addChild(this.dot);this.dot.x=this.dot.y=-16}MEye.prototype=new Sprite;
var CSound={ids:"over kick sword swosh tada unlock game_loop intro_loop".split(" "),queue:[],snds:[new Audio("snd/rollOver.ogg"),new Audio("snd/kick.ogg"),new Audio("snd/sword.ogg"),new Audio("snd/swosh.ogg"),new Audio("snd/tada.ogg"),new Audio("snd/unlock.ogg"),new Audio("snd/grow_up.ogg"),new Audio("snd/july_loop.ogg")],_active:{},on:!0,play:function(a,b,d){null==b&&(b=1);CSound.on&&(d=CSound.ind(a),d=CSound.snds[d],null!=CSound._active[a]&&CSound._active[a].stop(),CSound._active[a]=new Howl({src:[d.currentSrc],
loop:!0,volume:b}),CSound._active[a].play())},playOnce:function(a,b){null==b&&(b=1);if(CSound.on){var d=CSound.ind(a),d=CSound.snds[d];null!=CSound._active[a]&&CSound._active[a].stop();CSound._active[a]=new Howl({src:[d.currentSrc],volume:b});CSound._active[a].play()}},pause:function(a){CSound._active[a]&&CSound._active[a].pause()},stop:function(a){CSound._active[a]&&CSound._active[a].stop()},ind:function(a){return CSound.ids.indexOf(a)}};
!function(){var a=function(){this.init()};a.prototype={init:function(){var e=this||b;return e._codecs={},e._howls=[],e._muted=!1,e._volume=1,e._canPlayEvent="canplaythrough",e._navigator="undefined"!=typeof window&&window.navigator?window.navigator:null,e.masterGain=null,e.noAudio=!1,e.usingWebAudio=!0,e.autoSuspend=!0,e.ctx=null,e.mobileAutoEnable=!0,e._setup(),e},volume:function(e){var a=this||b;if(e=parseFloat(e),a.ctx||u(),"undefined"!=typeof e&&0<=e&&1>=e){if(a._volume=e,a._muted)return a;a.usingWebAudio&&
(a.masterGain.gain.value=e);for(var h=0;h<a._howls.length;h++)if(!a._howls[h]._webAudio)for(var d=a._howls[h]._getSoundIds(),r=0;r<d.length;r++){var g=a._howls[h]._soundById(d[r]);g&&g._node&&(g._node.volume=g._volume*e)}return a}return a._volume},mute:function(e){var a=this||b;a.ctx||u();a._muted=e;a.usingWebAudio&&(a.masterGain.gain.value=e?0:a._volume);for(var h=0;h<a._howls.length;h++)if(!a._howls[h]._webAudio)for(var d=a._howls[h]._getSoundIds(),r=0;r<d.length;r++){var g=a._howls[h]._soundById(d[r]);
g&&g._node&&(g._node.muted=!!e||g._muted)}return a},unload:function(){for(var e=this||b,a=e._howls.length-1;0<=a;a--)e._howls[a].unload();return e.usingWebAudio&&"undefined"!=typeof e.ctx.close&&(e.ctx.close(),e.ctx=null,u()),e},codecs:function(e){return(this||b)._codecs[e.replace(/^x-/,"")]},_setup:function(){var e=this||b;return e.state=e.ctx?e.ctx.state||"running":"running",e._autoSuspend(),e.noAudio||e._setupCodecs(),e},_setupCodecs:function(){var e=this||b,a="undefined"!=typeof Audio?new Audio:
null;if(!a||"function"!=typeof a.canPlayType)return e;var h=a.canPlayType("audio/mpeg;").replace(/^no$/,""),d=e._navigator&&e._navigator.userAgent.match(/OPR\/([0-6].)/g),d=d&&33>parseInt(d[0].split("/")[1],10);return e._codecs={mp3:!(d||!h&&!a.canPlayType("audio/mp3;").replace(/^no$/,"")),mpeg:!!h,opus:!!a.canPlayType('audio/ogg; codecs="opus"').replace(/^no$/,""),ogg:!!a.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,""),oga:!!a.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,
""),wav:!!a.canPlayType('audio/wav; codecs="1"').replace(/^no$/,""),aac:!!a.canPlayType("audio/aac;").replace(/^no$/,""),caf:!!a.canPlayType("audio/x-caf;").replace(/^no$/,""),m4a:!!(a.canPlayType("audio/x-m4a;")||a.canPlayType("audio/m4a;")||a.canPlayType("audio/aac;")).replace(/^no$/,""),mp4:!!(a.canPlayType("audio/x-mp4;")||a.canPlayType("audio/mp4;")||a.canPlayType("audio/aac;")).replace(/^no$/,""),weba:!!a.canPlayType('audio/webm; codecs="vorbis"').replace(/^no$/,""),webm:!!a.canPlayType('audio/webm; codecs="vorbis"').replace(/^no$/,
""),dolby:!!a.canPlayType('audio/mp4; codecs="ec-3"').replace(/^no$/,""),flac:!!(a.canPlayType("audio/x-flac;")||a.canPlayType("audio/flac;")).replace(/^no$/,"")},e},_enableMobileAudio:function(){var e=this||b,a=/iPhone|iPad|iPod|Android|BlackBerry|BB10|Silk|Mobi/i.test(e._navigator&&e._navigator.userAgent),h=!!("ontouchend"in window||e._navigator&&0<e._navigator.maxTouchPoints||e._navigator&&0<e._navigator.msMaxTouchPoints);if(!e._mobileEnabled&&e.ctx&&(a||h)){e._mobileEnabled=!1;e._mobileUnloaded||
44100===e.ctx.sampleRate||(e._mobileUnloaded=!0,e.unload());e._scratchBuffer=e.ctx.createBuffer(1,1,22050);var d=function(){var a=e.ctx.createBufferSource();a.buffer=e._scratchBuffer;a.connect(e.ctx.destination);"undefined"==typeof a.start?a.noteOn(0):a.start(0);a.onended=function(){a.disconnect(0);e._mobileEnabled=!0;e.mobileAutoEnable=!1;document.removeEventListener("touchend",d,!0)}};return document.addEventListener("touchend",d,!0),e}},_autoSuspend:function(){var e=this;if(e.autoSuspend&&e.ctx&&
"undefined"!=typeof e.ctx.suspend&&b.usingWebAudio){for(var a=0;a<e._howls.length;a++)if(e._howls[a]._webAudio)for(var h=0;h<e._howls[a]._sounds.length;h++)if(!e._howls[a]._sounds[h]._paused)return e;return e._suspendTimer&&clearTimeout(e._suspendTimer),e._suspendTimer=setTimeout(function(){e.autoSuspend&&(e._suspendTimer=null,e.state="suspending",e.ctx.suspend().then(function(){e.state="suspended";e._resumeAfterSuspend&&(delete e._resumeAfterSuspend,e._autoResume())}))},3E4),e}},_autoResume:function(){var e=
this;if(e.ctx&&"undefined"!=typeof e.ctx.resume&&b.usingWebAudio)return"running"===e.state&&e._suspendTimer?(clearTimeout(e._suspendTimer),e._suspendTimer=null):"suspended"===e.state?(e.state="resuming",e.ctx.resume().then(function(){e.state="running"}),e._suspendTimer&&(clearTimeout(e._suspendTimer),e._suspendTimer=null)):"suspending"===e.state&&(e._resumeAfterSuspend=!0),e}};var b=new a,d=function(e){return e.src&&0!==e.src.length?void this.init(e):void console.error("An array of source files must be passed with any new Howl.")};
d.prototype={init:function(e){return b.ctx||u(),this._autoplay=e.autoplay||!1,this._format="string"!=typeof e.format?e.format:[e.format],this._html5=e.html5||!1,this._muted=e.mute||!1,this._loop=e.loop||!1,this._pool=e.pool||5,this._preload="boolean"!=typeof e.preload||e.preload,this._rate=e.rate||1,this._sprite=e.sprite||{},this._src="string"!=typeof e.src?e.src:[e.src],this._volume=void 0!==e.volume?e.volume:1,this._duration=0,this._state="unloaded",this._sounds=[],this._endTimers={},this._queue=
[],this._onend=e.onend?[{fn:e.onend}]:[],this._onfade=e.onfade?[{fn:e.onfade}]:[],this._onload=e.onload?[{fn:e.onload}]:[],this._onloaderror=e.onloaderror?[{fn:e.onloaderror}]:[],this._onpause=e.onpause?[{fn:e.onpause}]:[],this._onplay=e.onplay?[{fn:e.onplay}]:[],this._onstop=e.onstop?[{fn:e.onstop}]:[],this._onmute=e.onmute?[{fn:e.onmute}]:[],this._onvolume=e.onvolume?[{fn:e.onvolume}]:[],this._onrate=e.onrate?[{fn:e.onrate}]:[],this._onseek=e.onseek?[{fn:e.onseek}]:[],this._webAudio=b.usingWebAudio&&
!this._html5,"undefined"!=typeof b.ctx&&b.ctx&&b.mobileAutoEnable&&b._enableMobileAudio(),b._howls.push(this),this._preload&&this.load(),this},load:function(){var e=null;if(b.noAudio)return void this._emit("loaderror",null,"No audio support.");"string"==typeof this._src&&(this._src=[this._src]);for(var a=0;a<this._src.length;a++){var h,d;if(this._format&&this._format[a])h=this._format[a];else{if(d=this._src[a],"string"!=typeof d){this._emit("loaderror",null,"Non-string found in selected audio sources - ignoring.");
continue}(h=/^data:audio\/([^;,]+);/i.exec(d))||(h=/\.([^.]+)$/.exec(d.split("?",1)[0]));h&&(h=h[1].toLowerCase())}if(b.codecs(h)){e=this._src[a];break}}return e?(this._src=e,this._state="loading","https:"===window.location.protocol&&"http:"===e.slice(0,5)&&(this._html5=!0,this._webAudio=!1),new g(this),this._webAudio&&k(this),this):void this._emit("loaderror",null,"No codec support for selected audio sources.")},play:function(e,a){var h=this,d=null;if("number"==typeof e)d=e,e=null;else{if("string"==
typeof e&&"loaded"===h._state&&!h._sprite[e])return null;if("undefined"==typeof e){e="__default";for(var m=0,g=0;g<h._sounds.length;g++)h._sounds[g]._paused&&!h._sounds[g]._ended&&(m++,d=h._sounds[g]._id);1===m?e=null:d=null}}var f=d?h._soundById(d):h._inactiveSound();if(!f)return null;if(d&&!e&&(e=f._sprite||"__default"),"loaded"!==h._state&&!h._sprite[e])return h._queue.push({event:"play",action:function(){h.play(h._soundById(f._id)?f._id:void 0)}}),f._id;if(d&&!f._paused)return a||setTimeout(function(){h._emit("play",
f._id)},0),f._id;h._webAudio&&b._autoResume();var k=0<f._seek?f._seek:h._sprite[e][0]/1E3,w=(h._sprite[e][0]+h._sprite[e][1])/1E3-k,q=1E3*w/Math.abs(f._rate);f._paused=!1;f._ended=!1;f._sprite=e;f._seek=k;f._start=h._sprite[e][0]/1E3;f._stop=(h._sprite[e][0]+h._sprite[e][1])/1E3;f._loop=!(!f._loop&&!h._sprite[e][2]);var l=f._node;if(h._webAudio)d=function(){h._refreshBuffer(f);l.gain.setValueAtTime(f._muted||h._muted?0:f._volume,b.ctx.currentTime);f._playStart=b.ctx.currentTime;"undefined"==typeof l.bufferSource.start?
f._loop?l.bufferSource.noteGrainOn(0,k,86400):l.bufferSource.noteGrainOn(0,k,w):f._loop?l.bufferSource.start(0,k,86400):l.bufferSource.start(0,k,w);q!==1/0&&(h._endTimers[f._id]=setTimeout(h._ended.bind(h,f),q));a||setTimeout(function(){h._emit("play",f._id)},0)},"loaded"===h._state?d():(h.once("load",d,f._id),h._clearTimer(f._id));else{var x=function(){l.currentTime=k;l.muted=f._muted||h._muted||b._muted||l.muted;l.volume=f._volume*b.volume();l.playbackRate=f._rate;setTimeout(function(){l.play();
q!==1/0&&(h._endTimers[f._id]=setTimeout(h._ended.bind(h,f),q));a||h._emit("play",f._id)},0)},d="loaded"===h._state&&(window&&window.ejecta||!l.readyState&&b._navigator.isCocoonJS);if(4===l.readyState||d)x();else{var n=function(){x();l.removeEventListener(b._canPlayEvent,n,!1)};l.addEventListener(b._canPlayEvent,n,!1);h._clearTimer(f._id)}}return f._id},pause:function(e,a){var b=this;if("loaded"!==b._state)return b._queue.push({event:"pause",action:function(){b.pause(e)}}),b;for(var d=b._getSoundIds(e),
m=0;m<d.length;m++){b._clearTimer(d[m]);var f=b._soundById(d[m]);if(f&&!f._paused){if(f._seek=b.seek(d[m]),f._rateSeek=0,f._paused=!0,b._stopFade(d[m]),f._node)if(b._webAudio){if(!f._node.bufferSource)break;"undefined"==typeof f._node.bufferSource.stop?f._node.bufferSource.noteOff(0):f._node.bufferSource.stop(0);b._cleanBuffer(f._node)}else isNaN(f._node.duration)&&f._node.duration!==1/0||f._node.pause();a||b._emit("pause",f._id)}}return b},stop:function(e,a){var b=this;if("loaded"!==b._state)return b._queue.push({event:"stop",
action:function(){b.stop(e)}}),b;for(var d=b._getSoundIds(e),m=0;m<d.length;m++){b._clearTimer(d[m]);var f=b._soundById(d[m]);if(f&&(f._seek=f._start||0,f._rateSeek=0,f._paused=!0,f._ended=!0,b._stopFade(d[m]),f._node))if(b._webAudio){if(!f._node.bufferSource)return a||b._emit("stop",f._id),b;"undefined"==typeof f._node.bufferSource.stop?f._node.bufferSource.noteOff(0):f._node.bufferSource.stop(0);b._cleanBuffer(f._node)}else isNaN(f._node.duration)&&f._node.duration!==1/0||(f._node.currentTime=f._start||
0,f._node.pause());f&&!a&&b._emit("stop",f._id)}return b},mute:function(e,a){var d=this;if("loaded"!==d._state)return d._queue.push({event:"mute",action:function(){d.mute(e,a)}}),d;if("undefined"==typeof a){if("boolean"!=typeof e)return d._muted;d._muted=e}for(var f=d._getSoundIds(a),m=0;m<f.length;m++){var g=d._soundById(f[m]);g&&(g._muted=e,d._webAudio&&g._node?g._node.gain.setValueAtTime(e?0:g._volume,b.ctx.currentTime):g._node&&(g._node.muted=!!b._muted||e),d._emit("mute",g._id))}return d},volume:function(){var e,
a,d=this,f=arguments;if(0===f.length)return d._volume;1===f.length||2===f.length&&"undefined"==typeof f[1]?0<=d._getSoundIds().indexOf(f[0])?a=parseInt(f[0],10):e=parseFloat(f[0]):2<=f.length&&(e=parseFloat(f[0]),a=parseInt(f[1],10));var g;if(!("undefined"!=typeof e&&0<=e&&1>=e))return g=a?d._soundById(a):d._sounds[0],g?g._volume:0;if("loaded"!==d._state)return d._queue.push({event:"volume",action:function(){d.volume.apply(d,f)}}),d;"undefined"==typeof a&&(d._volume=e);a=d._getSoundIds(a);for(var t=
0;t<a.length;t++)(g=d._soundById(a[t]))&&(g._volume=e,f[2]||d._stopFade(a[t]),d._webAudio&&g._node&&!g._muted?g._node.gain.setValueAtTime(e,b.ctx.currentTime):g._node&&!g._muted&&(g._node.volume=e*b.volume()),d._emit("volume",g._id));return d},fade:function(e,a,d,f){var h=this,m=e>a?"out":"in",g=Math.abs(e-a)/.01,v=0<g?d/g:d;if(4>v&&(g=Math.ceil(g/(4/v)),v=4),"loaded"!==h._state)return h._queue.push({event:"fade",action:function(){h.fade(e,a,d,f)}}),h;h.volume(e,f);for(var k=h._getSoundIds(f),q=0;q<
k.length;q++){var l=h._soundById(k[q]);if(l){if(f||h._stopFade(k[q]),h._webAudio&&!l._muted){var n=b.ctx.currentTime,u=n+d/1E3;l._volume=e;l._node.gain.setValueAtTime(e,n);l._node.gain.linearRampToValueAtTime(a,u)}var p=e;l._interval=setInterval(function(e,b){0<g&&(p+="in"===m?.01:-.01);p=Math.max(0,p);p=Math.min(1,p);p=Math.round(100*p)/100;h._webAudio?("undefined"==typeof f&&(h._volume=p),b._volume=p):h.volume(p,e,!0);p===a&&(clearInterval(b._interval),b._interval=null,h.volume(p,e),h._emit("fade",
e))}.bind(h,k[q],l),v)}}return h},_stopFade:function(e){var a=this._soundById(e);return a&&a._interval&&(this._webAudio&&a._node.gain.cancelScheduledValues(b.ctx.currentTime),clearInterval(a._interval),a._interval=null,this._emit("fade",e)),this},loop:function(){var e,a,b,d=arguments;if(0===d.length)return this._loop;if(1===d.length){if("boolean"!=typeof d[0])return b=this._soundById(parseInt(d[0],10)),!!b&&b._loop;this._loop=e=d[0]}else 2===d.length&&(e=d[0],a=parseInt(d[1],10));a=this._getSoundIds(a);
for(d=0;d<a.length;d++)(b=this._soundById(a[d]))&&(b._loop=e,this._webAudio&&b._node&&b._node.bufferSource&&(b._node.bufferSource.loop=e,e&&(b._node.bufferSource.loopStart=b._start||0,b._node.bufferSource.loopEnd=b._stop)));return this},rate:function(){var e,a,d=this,f=arguments;0===f.length?a=d._sounds[0]._id:1===f.length?0<=d._getSoundIds().indexOf(f[0])?a=parseInt(f[0],10):e=parseFloat(f[0]):2===f.length&&(e=parseFloat(f[0]),a=parseInt(f[1],10));var g;if("number"!=typeof e)return g=d._soundById(a),
g?g._rate:d._rate;if("loaded"!==d._state)return d._queue.push({event:"rate",action:function(){d.rate.apply(d,f)}}),d;"undefined"==typeof a&&(d._rate=e);a=d._getSoundIds(a);for(var k=0;k<a.length;k++)if(g=d._soundById(a[k])){g._rateSeek=d.seek(a[k]);g._playStart=d._webAudio?b.ctx.currentTime:g._playStart;g._rate=e;d._webAudio&&g._node&&g._node.bufferSource?g._node.bufferSource.playbackRate.value=e:g._node&&(g._node.playbackRate=e);var n=d.seek(a[k]),n=1E3*((d._sprite[g._sprite][0]+d._sprite[g._sprite][1])/
1E3-n)/Math.abs(g._rate);!d._endTimers[a[k]]&&g._paused||(d._clearTimer(a[k]),d._endTimers[a[k]]=setTimeout(d._ended.bind(d,g),n));d._emit("rate",g._id)}return d},seek:function(){var a,d,f=this,g=arguments;0===g.length?d=f._sounds[0]._id:1===g.length?0<=f._getSoundIds().indexOf(g[0])?d=parseInt(g[0],10):(d=f._sounds[0]._id,a=parseFloat(g[0])):2===g.length&&(a=parseFloat(g[0]),d=parseInt(g[1],10));if("undefined"==typeof d)return f;if("loaded"!==f._state)return f._queue.push({event:"seek",action:function(){f.seek.apply(f,
g)}}),f;var k=f._soundById(d);if(k){if(!("number"==typeof a&&0<=a))return f._webAudio?(a=f.playing(d)?b.ctx.currentTime-k._playStart:0,k._seek+((k._rateSeek?k._rateSeek-k._seek:0)+a*Math.abs(k._rate))):k._node.currentTime;var t=f.playing(d);t&&f.pause(d,!0);k._seek=a;k._ended=!1;f._clearTimer(d);t&&f.play(d,!0);!f._webAudio&&k._node&&(k._node.currentTime=a);f._emit("seek",d)}return f},playing:function(a){if("number"==typeof a)return a=this._soundById(a),!!a&&!a._paused;for(a=0;a<this._sounds.length;a++)if(!this._sounds[a]._paused)return!0;
return!1},duration:function(a){var e=this._duration;a=this._soundById(a);return a&&(e=this._sprite[a._sprite][1]/1E3),e},state:function(){return this._state},unload:function(){for(var a=this._sounds,d=0;d<a.length;d++){a[d]._paused||(this.stop(a[d]._id),this._emit("end",a[d]._id));this._webAudio||(a[d]._node.src="data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAAAAA=",a[d]._node.removeEventListener("error",a[d]._errorFn,!1),a[d]._node.removeEventListener(b._canPlayEvent,
a[d]._loadFn,!1));delete a[d]._node;this._clearTimer(a[d]._id);var g=b._howls.indexOf(this);0<=g&&b._howls.splice(g,1)}a=!0;for(d=0;d<b._howls.length;d++)if(b._howls[d]._src===this._src){a=!1;break}return f&&a&&delete f[this._src],b.noAudio=!1,this._state="unloaded",this._sounds=[],null},on:function(a,b,d,f){a=this["_on"+a];return"function"==typeof b&&a.push(f?{id:d,fn:b,once:f}:{id:d,fn:b}),this},off:function(a,b,d){var e=this["_on"+a];if(b)for(a=0;a<e.length;a++){if(b===e[a].fn&&d===e[a].id){e.splice(a,
1);break}}else if(a)this["_on"+a]=[];else for(b=Object.keys(this),a=0;a<b.length;a++)0===b[a].indexOf("_on")&&Array.isArray(this[b[a]])&&(this[b[a]]=[]);return this},once:function(a,b,d){return this.on(a,b,d,1),this},_emit:function(a,b,d){for(var e=this["_on"+a],f=e.length-1;0<=f;f--)e[f].id&&e[f].id!==b&&"load"!==a||(setTimeout(function(a){a.call(this,b,d)}.bind(this,e[f].fn),0),e[f].once&&this.off(a,e[f].fn,e[f].id));return this},_loadQueue:function(){var a=this;if(0<a._queue.length){var b=a._queue[0];
a.once(b.event,function(){a._queue.shift();a._loadQueue()});b.action()}return a},_ended:function(a){var e=a._sprite,e=!(!a._loop&&!this._sprite[e][2]);if(this._emit("end",a._id),!this._webAudio&&e&&this.stop(a._id,!0).play(a._id),this._webAudio&&e){this._emit("play",a._id);a._seek=a._start||0;a._rateSeek=0;a._playStart=b.ctx.currentTime;var d=1E3*(a._stop-a._start)/Math.abs(a._rate);this._endTimers[a._id]=setTimeout(this._ended.bind(this,a),d)}return this._webAudio&&!e&&(a._paused=!0,a._ended=!0,
a._seek=a._start||0,a._rateSeek=0,this._clearTimer(a._id),this._cleanBuffer(a._node),b._autoSuspend()),this._webAudio||e||this.stop(a._id),this},_clearTimer:function(a){return this._endTimers[a]&&(clearTimeout(this._endTimers[a]),delete this._endTimers[a]),this},_soundById:function(a){for(var b=0;b<this._sounds.length;b++)if(a===this._sounds[b]._id)return this._sounds[b];return null},_inactiveSound:function(){this._drain();for(var a=0;a<this._sounds.length;a++)if(this._sounds[a]._ended)return this._sounds[a].reset();
return new g(this)},_drain:function(){var a=this._pool,b=0,d;if(!(this._sounds.length<a)){for(d=0;d<this._sounds.length;d++)this._sounds[d]._ended&&b++;for(d=this._sounds.length-1;0<=d&&!(b<=a);d--)this._sounds[d]._ended&&(this._webAudio&&this._sounds[d]._node&&this._sounds[d]._node.disconnect(0),this._sounds.splice(d,1),b--)}},_getSoundIds:function(a){if("undefined"==typeof a){a=[];for(var b=0;b<this._sounds.length;b++)a.push(this._sounds[b]._id);return a}return[a]},_refreshBuffer:function(a){return a._node.bufferSource=
b.ctx.createBufferSource(),a._node.bufferSource.buffer=f[this._src],a._panner?a._node.bufferSource.connect(a._panner):a._node.bufferSource.connect(a._node),a._node.bufferSource.loop=a._loop,a._loop&&(a._node.bufferSource.loopStart=a._start||0,a._node.bufferSource.loopEnd=a._stop),a._node.bufferSource.playbackRate.value=a._rate,this},_cleanBuffer:function(a){if(this._scratchBuffer){a.bufferSource.onended=null;a.bufferSource.disconnect(0);try{a.bufferSource.buffer=this._scratchBuffer}catch(m){}}return a.bufferSource=
null,this}};var g=function(a){this._parent=a;this.init()};g.prototype={init:function(){var a=this._parent;return this._muted=a._muted,this._loop=a._loop,this._volume=a._volume,this._muted=a._muted,this._rate=a._rate,this._seek=0,this._paused=!0,this._ended=!0,this._sprite="__default",this._id=Math.round(Date.now()*Math.random()),a._sounds.push(this),this.create(),this},create:function(){var a=this._parent,d=b._muted||this._muted||this._parent._muted?0:this._volume;return a._webAudio?(this._node="undefined"==
typeof b.ctx.createGain?b.ctx.createGainNode():b.ctx.createGain(),this._node.gain.setValueAtTime(d,b.ctx.currentTime),this._node.paused=!0,this._node.connect(b.masterGain)):(this._node=new Audio,this._errorFn=this._errorListener.bind(this),this._node.addEventListener("error",this._errorFn,!1),this._loadFn=this._loadListener.bind(this),this._node.addEventListener(b._canPlayEvent,this._loadFn,!1),this._node.src=a._src,this._node.preload="auto",this._node.volume=d*b.volume(),this._node.load()),this},
reset:function(){var a=this._parent;return this._muted=a._muted,this._loop=a._loop,this._volume=a._volume,this._muted=a._muted,this._rate=a._rate,this._seek=0,this._rateSeek=0,this._paused=!0,this._ended=!0,this._sprite="__default",this._id=Math.round(Date.now()*Math.random()),this},_errorListener:function(){this._parent._emit("loaderror",this._id,this._node.error?this._node.error.code:0);this._node.removeEventListener("error",this._errorListener,!1)},_loadListener:function(){var a=this._parent;a._duration=
Math.ceil(10*this._node.duration)/10;0===Object.keys(a._sprite).length&&(a._sprite={__default:[0,1E3*a._duration]});"loaded"!==a._state&&(a._state="loaded",a._emit("load"),a._loadQueue());a._autoplay&&a.play();this._node.removeEventListener(b._canPlayEvent,this._loadFn,!1)}};var f={},k=function(a){var b=a._src;if(f[b])return a._duration=f[b].duration,void y(a);if(/^data:[^;]+;base64,/.test(b)){for(var d=atob(b.split(",")[1]),e=new Uint8Array(d.length),g=0;g<d.length;++g)e[g]=d.charCodeAt(g);z(e.buffer,
a)}else{var k=new XMLHttpRequest;k.open("GET",b,!0);k.responseType="arraybuffer";k.onload=function(){var b=(k.status+"")[0];return"0"!==b&&"2"!==b&&"3"!==b?void a._emit("loaderror",null,"Failed loading audio file with status: "+k.status+"."):void z(k.response,a)};k.onerror=function(){a._webAudio&&(a._html5=!0,a._webAudio=!1,a._sounds=[],delete f[b],a.load())};n(k)}},n=function(a){try{a.send()}catch(m){a.onerror()}},z=function(a,d){b.ctx.decodeAudioData(a,function(a){a&&0<d._sounds.length&&(f[d._src]=
a,y(d,a))},function(){d._emit("loaderror",null,"Decoding audio data failed.")})},y=function(a,b){b&&!a._duration&&(a._duration=b.duration);0===Object.keys(a._sprite).length&&(a._sprite={__default:[0,1E3*a._duration]});"loaded"!==a._state&&(a._state="loaded",a._emit("load"),a._loadQueue());a._autoplay&&a.play()},u=function(){b.noAudio=!1;try{"undefined"!=typeof AudioContext?b.ctx=new AudioContext:"undefined"!=typeof webkitAudioContext?b.ctx=new webkitAudioContext:b.usingWebAudio=!1}catch(h){b.usingWebAudio=
!1}if(!b.usingWebAudio)if("undefined"!=typeof Audio)try{var a=new Audio;"undefined"==typeof a.oncanplaythrough&&(b._canPlayEvent="canplay")}catch(h){b.noAudio=!0}else b.noAudio=!0;try{a=new Audio,a.muted&&(b.noAudio=!0)}catch(h){}var a=/iP(hone|od|ad)/.test(b._navigator&&b._navigator.platform),d=b._navigator&&b._navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/),d=d?parseInt(d[1],10):null;a&&d&&9>d&&(a=/safari/.test(b._navigator&&b._navigator.userAgent.toLowerCase()),(b._navigator&&b._navigator.standalone&&
!a||b._navigator&&!b._navigator.standalone&&!a)&&(b.usingWebAudio=!1));b.usingWebAudio&&(b.masterGain="undefined"==typeof b.ctx.createGain?b.ctx.createGainNode():b.ctx.createGain(),b.masterGain.gain.value=1,b.masterGain.connect(b.ctx.destination));b._setup()};"function"==typeof define&&define.amd&&define([],function(){return{Howler:b,Howl:d}});"undefined"!=typeof exports&&(exports.Howler=b,exports.Howl=d);"undefined"!=typeof window?(window.HowlerGlobal=a,window.Howler=b,window.Howl=d,window.Sound=
g):"undefined"!=typeof global&&(global.HowlerGlobal=a,global.Howler=b,global.Howl=d,global.Sound=g)}();
